# Generated by Django 3.0.4 on 2020-03-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('fulfill_at', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('restaurant_id', models.IntegerField(blank=True, null=True)),
                ('restaurant_name', models.CharField(blank=True, max_length=100)),
                ('client_id', models.IntegerField(blank=True, null=True)),
                ('client_first_name', models.CharField(blank=True, max_length=100)),
                ('client_last_name', models.CharField(blank=True, max_length=100)),
                ('missed_reason', models.CharField(blank=True, max_length=100)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sub_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('persons', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, max_length=100, null=True)),
            ],
        ),
    ]
