# Generated by Django 3.0.4 on 2020-05-12 12:50

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consegne',
            fields=[
                ('consegna_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_consegna', models.DateTimeField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_phone_number', models.CharField(blank=True, max_length=100)),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
            ],
        ),
    ]
