# Generated by Django 3.0.4 on 2020-05-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consegne',
            old_name='customer_name',
            new_name='indirizzo',
        ),
        migrations.RenameField(
            model_name='consegne',
            old_name='customer_phone_number',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='consegne',
            name='address',
        ),
        migrations.RemoveField(
            model_name='consegne',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='consegne',
            name='citta',
            field=models.CharField(choices=[('Schlieren', 'Schlieren'), ('Urdorf', 'Urdorf'), ('Dietikon', 'Dietikon'), ('Zurigo', 'Zurigo')], default='Schlieren', max_length=20),
        ),
        migrations.AddField(
            model_name='consegne',
            name='telefono',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='consegne',
            name='data_consegna',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
