# Generated by Django 3.0.4 on 2020-05-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20200512_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='consegne',
            name='richiesta',
            field=models.CharField(choices=[('telefono', 'telefono'), ('eat.ch', 'eat.ch'), ('uber', 'uber')], default='Telefono', max_length=20),
        ),
    ]
