# Generated by Django 3.0.4 on 2020-05-13 12:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_consegne_totale_ordine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consegne',
            name='citta',
            field=models.CharField(choices=[('Bergdietikon', 'Bergdietikon'), ('Dietikon', 'Dietikon'), ('Fahrweid', 'Fahrweid'), ('Geroldswil', 'Geroldswil'), ('Oberengstringen', 'Oberengstringen'), ('Schlieren', 'Schlieren'), ('Spreitenbach', 'Spreitenbach'), ('Unterengstringen', 'Unterengstringen'), ('Urdorf', 'Urdorf'), ('Weiningen', 'Weiningen'), ('Zurigo', 'Zurigo')], default='Schlieren', max_length=20),
        ),
        migrations.AlterField(
            model_name='consegne',
            name='totale_ordine',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
